In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('funcionarios_naragroup_sujo.csv', sep=';')
df

,id,nome,departamento,cargo,salario,data_admissao,email,ativo
0,32,Roberto Cardoso,FINANCEIRO,Assistente,11605.79,04/09/2022,roberto.cardoso@naragroup.com,S
1,93,Amanda Silva,Financeiro,Coordenador,10032.2,09/08/2019,amanda.silva@naragroup.com,S
2,52,Jefferson Lima,T.I.,Estagiário,7387.84,2021-06-13,jefferson.lima@naragroup.com,1
3,81,Aissa Pereira,Tecnologia,Analista,10376.08,Nov-2018,aissa.pereira@naragroup.com,True
4,7,Patrícia Rocha,FINANCEIRO,Assistente,"""14859,19""",2023-12-29,patrícia.rocha@naragroup.com,SIM
...,...,...,...,...,...,...,...,...
95,42,Willian Duarte,Recursos Humanos,Analista,6032.64,Jan-2018,willian.duarte@naragroup.com,1
96,16,Rodrigo Batista,Vend.,Gerente,13975.81,16/04/2024,rodrigo.batista@naragroup.com,True
97,99,Viviane Gomes,R.H.,Diretor,9935.7,20/05/2020,viviane.gomes@naragroup.com,1
98,3,Fernanda Costa,FINANCEIRO,Coordenador,11250.05,2024-08-07,fernanda.costa@naragroup.com,True
99,75,Graciela Silva,vendas,Estagiário,4941.37,Jun-2024,graciela.silva@naragroup.com,sim

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             100 non-null    int64
 1   nome           100 non-null    str
 2   departamento   100 non-null    str
 3   cargo          100 non-null    str
 4   salario        90 non-null     str
 5   data_admissao  100 non-null    str
 6   email          92 non-null     str
 7   ativo          100 non-null    str
dtypes: int64(1), str(7)
memory usage: 6.4 KB

In [6]:
# tipos de cada coluna
df.dtypes

id               int64
nome               str
departamento       str
cargo              str
salario            str
data_admissao      str
email              str
ativo              str
dtype: object

In [7]:
df.describe()

               id
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [8]:
df.describe(include='object')

C:\Users\vitor.jsouza\AppData\Local\Temp\ipykernel_17552\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,nome,departamento,cargo,salario,data_admissao,email,ativo
count,100,100,100,90,100,92,100
unique,90,31,6,82,86,83,7
top,Amanda Silva,vendas,Assistente,10032.2,09/08/2019,amanda.silva@naragroup.com,1
freq,2,8,22,2,2,2,22

In [10]:
# Contagem de nulos por coluna
df.isnull().sum().reset_index()

           index   0
0             id   0
1           nome   0
2   departamento   0
3          cargo   0
4        salario  10
5  data_admissao   0
6          email   8
7          ativo   0

In [11]:
# Percentual de nulos — colunas com >15% exigem atenção especial
(df.isnull().sum() / len(df) * 100).round(1)   # /len conta a quantidade de linhas que tem na coluna

id                0.0
nome              0.0
departamento      0.0
cargo             0.0
salario          10.0
data_admissao     0.0
email             8.0
ativo             0.0
dtype: float64

In [12]:
# Ver QUAIS linhas têm pelo menos um nulo
df[df.isnull() # Gera True/False para cada dado (True = nulo)
.any(axis=1)] # any(): existe pelo menos um True? axis=1: por linha

,id,nome,departamento,cargo,salario,data_admissao,email,ativo
11,94,Guilherme Santos,operacoes,Coordenador,7220.62,Mar-2022,NaN,1
14,96,Carla Peixoto,ti,Coordenador,NaN,Nov-2023,carla.peixoto@naragroup.com,Sim
15,53,Carla Peixoto,ti,Coordenador,NaN,Nov-2023,carla.peixoto@naragroup.com,Sim
17,70,César Gomes,OPERAÇÕES,Gerente,12852.17,2020-11-16,NaN,1
20,58,Hélio Braga,marketing,Assistente,3168.67,2022-10-18,NaN,Sim
21,46,Alexandre Lacerda,Financeiro,Estagiário,11962.92,2020-07-29,NaN,Sim
32,95,Mariana Correia,FINANCEIRO,Assistente,NaN,2022-01-21,mariana.correia@naragroup.com,1
35,34,Leandro Reis,Operações,Analista,12386.09,Nov-2018,NaN,Sim
41,22,Anderson Cruz,RH,Estagiário,11229.79,Jun-2020,NaN,1
42,77,Andréia Campos,RH,Assistente,NaN,2018-08-17,andréia.campos@naragroup.com,sim
44,65,Tatiana Ferreira,T.I.,Gerente,NaN,2022-10-30,tatiana.ferreira@naragroup.com,Sim
47,41,Claudia Ramos,tecnologia da informação,Gerente,NaN,2023-11-13,claudia.ramos@naragroup.com,Sim
50,17,Mariana Correia,FINANCEIRO,Assistente,NaN,2022-01-21,mariana.correia@naragroup.com,1
51,29,Flávia Azevedo,vendas,Estagiário,NaN,05/08/2020,flávia.azevedo@naragroup.com,True
55,89,Keila Mendes,T.I.,Coordenador,NaN,Oct-2018,keila.mendes@naragroup.com,sim
67,5,Juliana Martins,marketing,Analista,NaN,Dec-2023,juliana.martins@naragroup.com,True
75,10,Lucas Ribeiro,OPERAÇÕES,Analista,2982.2,03/12/2019,NaN,1
91,82,Guilherme Santos,operacoes,Coordenador,7220.62,Mar-2022,NaN,1

In [13]:
# Quantidade de duplicatas
df.duplicated().sum()

np.int64(0)

In [14]:
# Visualizar TODAS as ocorrências duplicadas
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [id, nome, departamento, cargo, salario, data_admissao, email, ativo]
Index: []

In [19]:
# Duplicata apenas por colunas-chave
df[df.duplicated(subset=['nome','departamento','cargo','salario','data_admissao','email','ativo'], keep=False)].sort_values(by='nome')

,id,nome,departamento,cargo,salario,data_admissao,email,ativo
1,93,Amanda Silva,Financeiro,Coordenador,10032.2,09/08/2019,amanda.silva@naragroup.com,S
28,11,Amanda Silva,Financeiro,Coordenador,10032.2,09/08/2019,amanda.silva@naragroup.com,S
22,98,Beatriz Almeida,operações,Analista,"""13331,89""",2019-10-24,beatriz.almeida@naragroup.com,True
56,55,Beatriz Almeida,operações,Analista,"""13331,89""",2019-10-24,beatriz.almeida@naragroup.com,True
14,96,Carla Peixoto,ti,Coordenador,NaN,Nov-2023,carla.peixoto@naragroup.com,Sim
15,53,Carla Peixoto,ti,Coordenador,NaN,Nov-2023,carla.peixoto@naragroup.com,Sim
57,92,Déborah Cunha,RH,Assistente,8191.9,Feb-2019,déborah.cunha@naragroup.com,Sim
59,73,Déborah Cunha,RH,Assistente,8191.9,Feb-2019,déborah.cunha@naragroup.com,Sim
10,100,Fábio Sampaio,vendas,Analista,3650.49,2022-05-14,fábio.sampaio@naragroup.com,1
43,76,Fábio Sampaio,vendas,Analista,3650.49,2022-05-14,fábio.sampaio@naragroup.com,1
11,94,Guilherme Santos,operacoes,Coordenador,7220.62,Mar-2022,NaN,1
91,82,Guilherme Santos,operacoes,Coordenador,7220.62,Mar-2022,NaN,1
32,95,Mariana Correia,FINANCEIRO,Assistente,NaN,2022-01-21,mariana.correia@naragroup.com,1
50,17,Mariana Correia,FINANCEIRO,Assistente,NaN,2022-01-21,mariana.correia@naragroup.com,1
81,91,Patrícia Rocha,FINANCEIRO,Assistente,"""14859,19""",2023-12-29,patrícia.rocha@naragroup.com,SIM
4,7,Patrícia Rocha,FINANCEIRO,Assistente,"""14859,19""",2023-12-29,patrícia.rocha@naragroup.com,SIM
8,25,Priscila Teixeira,vendas,Coordenador,13401.31,Aug-2022,priscila.teixeira@naragroup.com,True
68,97,Priscila Teixeira,vendas,Coordenador,13401.31,Aug-2022,priscila.teixeira@naragroup.com,True
19,85,Viviane Gomes,R.H.,Diretor,9935.7,20/05/2020,viviane.gomes@naragroup.com,1
97,99,Viviane Gomes,R.H.,Diretor,9935.7,20/05/2020,viviane.gomes@naragroup.com,1

In [21]:
# Ver variações do departamento
df['departamento'].value_counts().reset_index()

                departamento  count
0                     vendas      8
1                 FINANCEIRO      7
2                 Tecnologia      6
3                        RH       6
4                       T.I.      5
5                  Operações      5
6           Recursos Humanos      5
7                     VENDAS      5
8                 Financeiro      4
9                  operacoes      4
10                      Fin.      4
11                 OPERAÇÕES      4
12                 marketing      4
13                 MARKETING      3
14                marketing       3
15                      R.H.      3
16                     Oper.      3
17                        ti      2
18                operações       2
19                        RH      2
20  tecnologia da informação      2
21               financeiro       2
22                     Vend.      2
23                financeiro      2
24                        rh      1
25                    Vendas      1
26                       Mkt      1
27                   vendas       1
28                 Marketing      1
29                       TI       1
30                        TI      1