In [1]:
import pandas as pd

import numpy as np

In [4]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding = 'latin1', sep=';')
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [17]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index() # informação qualitativa utilizo parenteses (''); informação quantitativa utilizo colchetes ['']; reset_index() após o sum() visualizo o index
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False) # ascending = False visualiza a linha do menor para o maior, ordeno as linhas da coluna
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [14]:
array_roubo_veiculo_dp = np.array(df_roubo_veiculo_dp['roubo_veiculo'])

In [21]:
media = np.mean(array_roubo_veiculo_dp)
mediana = np.median(array_roubo_veiculo_dp)
q1 = np.percentile(array_roubo_veiculo_dp, 25)
q2 = np.percentile(array_roubo_veiculo_dp, 50)
q3 = np.percentile(array_roubo_veiculo_dp, 75)
print(f'Média {media}')
print(f'Mediana {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

Média 5250.840579710145
Mediana 1227.0
Q1: 103.75
Q2: 1227.0
Q3: 8117.5

In [25]:
distancia = (media - mediana) / mediana  # Número percentual por isso sai um percentual, depois é só formatar para %
print(distancia)

print(f'{distancia:.2%}')

3.279413675395391
327.94%

In [16]:
df_top_25_roubo = df_roubo_veiculo_dp.loc[df_roubo_veiculo_dp['roubo_veiculo'] >q3]
df_top_25_roubo

    cisp  roubo_veiculo
52    59          37780
57    64          32839
35    39          29663
23    27          27920
30    34          27543
47    54          24945
53    60          20696
34    38          20044
17    21          19790
31    35          19422
36    40          19403
65    74          18414
29    33          18069
25    29          16895
51    58          16351
45    52          15653
18    22          15193
27    31          15122
40    44          14912
63    72          14212
64    73          14000
26    30          12866
50    57          12516
20    24          12108
49    56          12019
21    25          11076
24    28          11057
19    23          10803
66    75          10165
55    62           9279
16    20           9124
28    32           8694
69    78           8571
46    53           8567
62    71           8203

In [28]:
df_rb_veic_baix = df.loc[df['munic'] == 'Baixada Fluminense']
df_rb_veic_baix = df_rb_veic_baix.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_rb_veic_baix = df_rb_veic_baix.sort_values(by = 'roubo_veiculo', ascending = False)

In [29]:
array= np.array(df_rb_veic_baix['roubo_veiculo'])

In [31]:
q1 = np.percentile(array_roubo_veiculo_dp, 25)
q2 = np.percentile(array_roubo_veiculo_dp, 50)
q3 = np.percentile(array_roubo_veiculo_dp, 75)
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

Q1: 103.75
Q2: 1227.0
Q3: 8117.5

In [34]:
df_top_25_roub_veic_baix = df_roubo_veiculo_dp.loc[df_roubo_veiculo_dp['roubo_veiculo'] >q3]
df_top_25_roub_veic_baix

    cisp  roubo_veiculo
52    59          37780
57    64          32839
35    39          29663
23    27          27920
30    34          27543
47    54          24945
53    60          20696
34    38          20044
17    21          19790
31    35          19422
36    40          19403
65    74          18414
29    33          18069
25    29          16895
51    58          16351
45    52          15653
18    22          15193
27    31          15122
40    44          14912
63    72          14212
64    73          14000
26    30          12866
50    57          12516
20    24          12108
49    56          12019
21    25          11076
24    28          11057
19    23          10803
66    75          10165
55    62           9279
16    20           9124
28    32           8694
69    78           8571
46    53           8567
62    71           8203

In [35]:
df_ap_menores = df.groupby('cisp')['aaapai'].sum().reset_index()
df_ap_menores = df_ap_menores.sort_values(by='aaapai', ascending = False)
df_ap_menores

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [37]:
array_df_ap_menores = np.array(df_ap_menores)
media = np.mean(array_df_ap_menores)
mediana = np.median(array_df_ap_menores)
print(f'Média {media}')
print(f'Mediana {mediana}')

Média 495.3804347826087
Mediana 135.5

In [38]:
distancia = (media - mediana) / mediana  # Número percentual por isso sai um percentual, depois é só formatar para %
print(distancia)

print(f'{distancia:.2%}')

2.6559441681373337
265.59%

In [45]:
df_roub_rua_dp = df.groupby('cisp')['roubo_rua'].sum().reset_index()
df_roub_rua_dp = df_roub_rua_dp.sort_values(by='roubo_rua', ascending = False)
df_roub_rua_dp

     cisp  roubo_rua
52     59      87859
57     64      64737
30     34      58326
25     29      50126
65     74      47594
..    ...        ...
131   157         16
130   156         11
94    111          7
77     92          6
129   155          5

[138 rows x 2 columns]

In [46]:
array_df_roub_rua_dp = np.array(df_roub_rua_dp)
media = np.mean(array_df_roub_rua_dp)
mediana = np.median(array_df_roub_rua_dp)
print(f'Média {media}')
print(f'Mediana {mediana}')

Média 6558.315217391304
Mediana 134.5

In [47]:
distancia = (media - mediana) / mediana  # Número percentual por isso sai um percentual, depois é só formatar para %
print(distancia)

print(f'{distancia:.2%}')

47.76070793599482
4776.07%